language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-senc' ]; then cd .. && eval "mv $currentfolder generator-senc" && cd generator-senc; fi

